name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: yarn install
        run: |
          yarn install

      - name: yarn test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_HARD_LINKS: false # because of https://github.com/electron-userland/electron-builder/issues/3179
        run: |
          yarn run package
          yarn run test
          yarn run lint
